[project]
name = "tontraeger"
version = "0.1.0"
description = "Control Sonos with RFID tags"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.0",
    "mfrc522>=0.0.3; sys_platform == 'linux'",
    "python-dotenv>=1.0.1",
    "RPi.GPIO>=0.7.1; sys_platform == 'linux'",
    "soco>=0.30.0",
]

[tool.ruff]
# Ruff configuration settings
lint.select = ["E", "F", "B", "ANN"]
lint.ignore = ["E501"]
line-length = 100

[tool.mypy]
# MyPy configuration settings
python_version = 3.11
warn_unused_configs = true
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.0",
    "ruff>=0.9.6",
]
